using System;
using System.IO;
using System.Linq;
using System.Text;
using Mono.Cecil;

// Code generator. Two source-of-truth mirrors from the REAL game assembly so the mod is DRY + type-safe:
//   1. GameEnums.generated.cs — mirror enums that PURE Core needs (Core can't reference the game DLL).
//   2. GameRef.generated.cs   — verified member-NAME constants for the few private members we reach by
//      reflection (the only place the compiler can't check). Generation FAILS if a named member is missing,
//      and a contract test re-asserts both, so a game update can't silently break us.
//
// Discipline: only generate what the mod depends on. Direct typed access is already compile-checked.
// Run: dotnet run --project tools/CommanderLayer.CodeGen   (needs lib/Assembly-CSharp.dll)

// Enums PURE Core reasons about (classifier). Add here only when Core uses one.
string[] enumsToMirror = { "VehicleType", "ShipType", "BuildingType" };

// Private members reached via reflection: (type, member). Verified to exist at generation time.
(string Type, string Member)[] reflectedMembers =
{
    ("VirtualMFD", "leftButtons"),
    ("VirtualMFD", "rightButtons"),
    ("VirtualMFD", "leftScreens"),
    ("VirtualMFD", "rightScreens"),
};

string repoRoot = FindRepoRoot() ?? throw new Exception("Could not find repo root (lib/Assembly-CSharp.dll).");
string dllPath = Path.Combine(repoRoot, "lib", "Assembly-CSharp.dll");
string genDir = Path.Combine(repoRoot, "src", "Core", "Generated");
Directory.CreateDirectory(genDir);

var resolver = new DefaultAssemblyResolver();
resolver.AddSearchDirectory(Path.Combine(repoRoot, "lib"));
using var asm = AssemblyDefinition.ReadAssembly(dllPath, new ReaderParameters { AssemblyResolver = resolver });
var module = asm.MainModule;

// Resolve types by SIMPLE name (handles namespaced/nested types without hardcoding namespaces).
TypeDefinition FindType(string simpleName) =>
    module.GetTypes().FirstOrDefault(t => t.Name == simpleName);

// ---- 1. enums ----
var e = new StringBuilder();
e.AppendLine("// <auto-generated> by tools/CommanderLayer.CodeGen from Assembly-CSharp.dll. DO NOT EDIT.");
e.AppendLine("//   Regenerate via scripts/generate-types.sh. Drift is asserted by a contract test.");
e.AppendLine("#pragma warning disable CS1591");
e.AppendLine();
e.AppendLine("namespace CommanderLayer.Core.Generated");
e.AppendLine("{");
foreach (var name in enumsToMirror)
{
    var t = FindType(name);
    if (t == null || !t.IsEnum) throw new Exception($"Enum '{name}' not found in Assembly-CSharp.");
    e.AppendLine($"    /// <summary>Mirror of game enum <c>{name}</c>.</summary>");
    e.AppendLine($"    public enum {name}");
    e.AppendLine("    {");
    foreach (var f in t.Fields.Where(f => f.IsLiteral && f.Name != "value__"))
        e.AppendLine($"        {f.Name} = {Convert.ToInt64(f.Constant)},");
    e.AppendLine("    }");
    e.AppendLine();
}
e.AppendLine("}");
File.WriteAllText(Path.Combine(genDir, "GameEnums.generated.cs"), e.ToString());

// ---- 2. reflected member-name constants (verified) ----
var r = new StringBuilder();
r.AppendLine("// <auto-generated> by tools/CommanderLayer.CodeGen from Assembly-CSharp.dll. DO NOT EDIT.");
r.AppendLine("//   Verified member names for reflection seams (no magic strings). Regenerate via scripts/generate-types.sh.");
r.AppendLine("#pragma warning disable CS1591");
r.AppendLine();
r.AppendLine("namespace CommanderLayer.Core.Generated");
r.AppendLine("{");
r.AppendLine("    /// <summary>Verified names of private game members the mod reaches by reflection.</summary>");
r.AppendLine("    public static class GameRef");
r.AppendLine("    {");
foreach (var (type, member) in reflectedMembers)
{
    var t = FindType(type) ?? throw new Exception($"Type '{type}' not found in Assembly-CSharp.");
    bool exists = t.Fields.Any(f => f.Name == member)
                  || t.Methods.Any(m => m.Name == member)
                  || t.Properties.Any(p => p.Name == member);
    if (!exists) throw new Exception($"Member '{type}.{member}' not found in Assembly-CSharp (game changed?).");
    r.AppendLine($"        public const string {type}_{member} = \"{member}\";");
}
r.AppendLine("    }");
r.AppendLine("}");
File.WriteAllText(Path.Combine(genDir, "GameRef.generated.cs"), r.ToString());

Console.WriteLine($"Generated {enumsToMirror.Length} enum(s) + {reflectedMembers.Length} member const(s) -> {genDir}");
return 0;

static string FindRepoRoot()
{
    foreach (var start in new[] { Directory.GetCurrentDirectory(), AppContext.BaseDirectory })
    {
        var dir = new DirectoryInfo(start);
        while (dir != null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "lib", "Assembly-CSharp.dll"))) return dir.FullName;
            dir = dir.Parent;
        }
    }
    return null;
}
